### ISSUE TITLE
Support sending to bech32m

### ISSUE THREAD

**Issue by kingonly** [breez/breezmobile#946]
https://en.bitcoin.it/wiki/Bech32_adoption

Need to check with Boltz & validate status after 0.15 merge.

**Comment by darosior** [comment]
Any update on this? Sending support should be a [tiny code change](https://whentaproot.org/#adding-bech32m).

**Comment by kingonly** [comment]
@ubbabeck please check the status with Boltz and add to your todos

**Comment by Xekyo** [comment]
Given the recent mempool dynamics, I could see more blockspace efficient output types get a bit more attention

**Comment by ubbabeck** [comment]
> Given the recent mempool dynamics, I could see more blockspace efficient output types get a bit more attention

Agree, will allocate time to implement sending to bech32m.

**Comment by ubbabeck** [comment]
# Todo

- [ ] Add `p2tr` to dev console 

## Reverse swap

- [ ] Add taproot address to claim transaction in `breez/boltz` 
- [ ] Sign claim transaction using Schnorr

## Submarine swap

- [ ] Use taproot in `SubmarineSwap` in `breez/lnd`
- [ ] Find out if 
- [ ] Update to tapscript in the lnd `submarineswap` package 
- [ ] Sign using Schnorr for `Redeem`

## Feel free to add comment or suggestions.

**Comment by ubbabeck** [comment]
# Todo

- [ ] Add `p2tr` to dev console 

## Reverse swap

- [ ] Add taproot address to claim transaction in `breez/boltz` 
- [ ] Sign claim transaction using Schnorr

## Submarine swap

`SubmarineSwap` in `breez/lnd`
- [ ] refund to taproot pubkey

## Unexpected funds

- [ ] allow for`p2tr` in sweep transaction 

## Feel free to add comment or suggestions.
